var express = require('express');
var router = express.Router();

/* GET users listing. */
// auto generated by express. not me
router.get('/', function(req, res, next) {
  res.send('respond with a resource');
});

module.exports = router;
